# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-Datasheet-DBI
version:      0.8
version_from: lib/Gtk2/Ex/Datasheet/DBI.pm
installdirs:  site
requires:
    DBI:                           1.3
    Gtk2:                          1.04
    Gtk2::Ex::Dialogs:             0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
